language: node_js
cache:
directories:
  - node_modules
notifications:
email:false
node_js:
  - '8'
branches:
except:
  - /^v\d+\.\d+\.\d+$/
env:
   global:
    secure: Gu/NadwKmBTokXxPpuz8NS2U7HuwybVqDtwbLPGi8iEKkAn5pOylcg7V/AECtKNyRB42v8l2FoJgaQmUfy4PGDNriZPBeHbMpa29N1DHBEAYfiIP19nLghk1rzZvpndVEH6gRgRS5lWrlU5avwYUIW/t8RiqsYptkM6C/pUQVxWJgJAs5n8WMaXiaGMoC9pxOFp5Nipt7KIJ0vPSKo1N4LqKNdXaAaTNsqDMpjKW1wysSey6SkRpkN21IY3A50nkEh/ZdBI+TObXHhUg7w+xBzwWZGp7dUNjWwOSlIMxbV0ScKsujRSKFrbnDxCOiTFWa7uChN/sFaBV1aguMogrv37tQr14q01e8ZO5jmZB3VkQgGqsDEjiWRO+eQDOnbAKCdiceaTyKwp/KtsRrd2cvAIqylD0ZwaBYE2SO50pAWIrcbU4qCDnd6GJuje0hXnkBFLoYpRJg5qWKw+7GK10Ece6fWdO2JWTnzisjXg43I4sDw0YmBLN4z7dAPiukKSCFGfXMqIYMyXGet+3Hi6Egk5vjwlb7OXYMYDT3XUX5JPO4+oBpuMx8t/5oQD1Sc0+LeHNGPfgwb0kxUk2pA3D/e76trv+EVyDbBT+jEaqU01S/KHnruimzdWIj9mGKif9t2/jNbQn26Kb0yaTcXugGjLJTmlkAp6eSJO+yap673Q=

